// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZI3973H4_CiVTxUh1se-exvF0nWFiBj0',
    appId: '1:755320089018:web:3304ef4628ade7bf435583',
    messagingSenderId: '755320089018',
    projectId: 'evident-post-452016-h3',
    authDomain: 'evident-post-452016-h3.firebaseapp.com',
    storageBucket: 'evident-post-452016-h3.firebasestorage.app',
    measurementId: 'G-JTDBV9BFC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3eyXlvidDQtgtF6V2xaE4WQEPgfbA6eg',
    appId: '1:755320089018:android:c12f6e50ca29b191435583',
    messagingSenderId: '755320089018',
    projectId: 'evident-post-452016-h3',
    storageBucket: 'evident-post-452016-h3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9AawAPx5NMoO3JPXQDXrqQy2C7BJZ4NM',
    appId: '1:755320089018:ios:433e510df992a645435583',
    messagingSenderId: '755320089018',
    projectId: 'evident-post-452016-h3',
    storageBucket: 'evident-post-452016-h3.firebasestorage.app',
    iosBundleId: 'com.example.nomardTiktokFinal',
  );

}